# Generated by Django 5.1.5 on 2025-01-19 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_mymovies_user_alter_comment_user_and_more'),
        ('main_app', '0002_alter_mymovies_user_alter_watchlist_user_and_more'),
        ('main_app', '0002_alter_review_user_alter_mymovies_user_and_more'),
    ]

    operations = [
    ]
