# Generated by Django 5.1.5 on 2025-01-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_merge_20250119_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year_made',
            field=models.IntegerField(default=2000),
        ),
    ]
