# Generated by Django 5.1.5 on 2025-01-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_movie_year_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', to='main_app.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year_made',
            field=models.IntegerField(),
        ),
    ]
